apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/O-Hahn/todo-app-oh.git
    contextDir: 
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile    # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
  output:
    to:
      kind: ImageStreamTag
      name: todo-app:latest